#!/bin/sh

set -e

COVERALLS_URL="https://coveralls.io/api/v1/jobs"
docker run -it --rm -v "$PWD":/usr/src/app -w /usr/src/app clojure lein test

docker run -it --rm -v "$PWD":/usr/src/app -w /usr/src/app clojure lein cloverage --coveralls

curl -F 'json_file=@coveralls.json' "$COVERALLS_URL"
